### PR TITLE
WOAINFRA-2831 - RN73 Updates

### PR DESCRIPTION
**Pull request by kochavi-daniel**
Add Gradle 8 required changes.

### CODE REVIEW

**Comment by Inbal-Tish** [comment]
@kochavi-daniel Seems good but please add a description to the PR.
Also, I think the base of the PR might be off - you have all of me previous changes here...

**Comment by kochavi-daniel** [comment]
@Inbal-Tish I branched off of latest master

**Comment by Inbal-Tish** [comment]
@kochavi-daniel You're branching off 'aMarCruz:master', not this fork's master

**Comment by Inbal-Tish** [comment]
> @Inbal-Tish I branched off of latest master
The PR is on the library, not the fork

**Pull request closed without merging**
